In [5]:
import src.dataset
from src.dataset import get_data_loader


In [14]:
import importlib
importlib.reload(src.dataset)

<module 'src.dataset' from 'd:\\deeplearning\\动手学深度学习\\competition\\california_house_prices\\src\\dataset.py'>

In [15]:
train_iter = get_data_loader("./data/raw/train.csv", batch_size=256, num_rare=3)

d:\deeplearning\动手学深度学习\competition\california_house_prices\src\dataset.py:42: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  categorical.loc[:, name] = le.fit_transform(feature)
d:\deeplearning\动手学深度学习\competition\california_house_prices\src\dataset.py:42: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  categorical.loc[:, name] = le.fit_transform(feature)
d:\deeplearning\动手学深度学习\competition\california_house_prices\src\dataset.py:42: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice fro

In [16]:
num, cat, lab = next(iter(train_iter))

In [17]:
num.shape

torch.Size([256, 18])

In [18]:
cat.shape

torch.Size([256, 11])

In [19]:
lab.shape

torch.Size([256])

In [20]:
num[0]

tensor([-0.1141, -0.0192,  0.5420,  0.9395, -0.0045,  0.0480,  0.0567,  1.5590,
        -0.3226,  1.8389, -0.5650, -0.0677, -0.2532,  0.6912,  0.6738,  0.2983,
         0.6088,  0.3494])

In [21]:
cat[0]

tensor([ 33,  23,  43, 643, 586, 139,  60, 449, 382, 220, 353])

In [1]:
import torch

In [2]:
from src.model import HouseNet

In [3]:
num_types=[100, 245, 310, 780, 25, 1000, 56, 79, 256, 77, 99]
num_embs = [10, 15, 20, 30, 5, 35, 8, 9, 15, 9, 10]
net = HouseNet(num_types=num_types, num_embs=num_embs, num_numeric=18)

In [11]:
x_num = torch.randn(size=(1, 18))
x_cat = torch.tensor([50, 121, 128, 450, 12, 546, 28, 70, 240, 1, 20], dtype=torch.long).reshape(1, -1)

In [12]:
net(x_num, x_cat)

tensor([[0.0282]], grad_fn=<AddmmBackward0>)

In [8]:
print(net)

HouseNet(
  (embeddings): ModuleList(
    (0): Embedding(100, 10)
    (1): Embedding(245, 15)
    (2): Embedding(310, 20)
    (3): Embedding(780, 30)
    (4): Embedding(25, 5)
    (5): Embedding(1000, 35)
    (6): Embedding(56, 8)
    (7): Embedding(79, 9)
    (8): Embedding(256, 15)
    (9): Embedding(77, 9)
    (10): Embedding(99, 10)
  )
  (mlp): Sequential(
    (0): Linear(in_features=184, out_features=128, bias=True)
    (1): ReLU()
    (2): Linear(in_features=128, out_features=64, bias=True)
    (3): ReLU()
    (4): Linear(in_features=64, out_features=1, bias=True)
  )
)
